from . import res_partner
from . import stock_location
from . import product
from . import consignment_transfer
from . import stock_warehouse
from . import stock_picking
from . import stock_move
from . import sale
from . import consignment_stock_report
from . import consignment_return
