# -*- coding: utf-8 -*-
{
    'name': 'Consignment Management',
    'version': '1.2',
    'summary': 'All consignment management features.',
    'category': 'Inventory',
    'Author': 'Asia Matrix Software Solution',
    'website': "www.asiamatrixsoftware.com",
    'email': 'info@asiamatrixsoftware.com',
    'depends': [
        'account',
        'sale_extend',
        'stock',
        'contacts',
        'multi_branches',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/consignment_data.xml',
        'data/ir_sequences.xml',
        'views/res_partner_views.xml',
        'views/stock_location_views.xml',
        'views/product_views.xml',
        'views/consignment_transfer_views.xml',
        'views/consignment_return_views.xml',
        'views/stock_warehouse_views.xml',
        'views/sale_views.xml',
        'views/stock_picking_views.xml',
        'views/consignment_stock_report_views.xml',
        'reports/consignment_report_views.xml',
        'views/consignment_menuitems.xml',
        'wizards/consignment_transfer_wizard_views.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
